services:
  - type: web
    name: ilmforge-erp
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
