/**
 * IlmForge — Transport Management
 * Full module with KPI cards, route management, and printable reports
 * exactly matching the reference screenshots
 */
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import api from '../../api/client';
import { Plus, Truck, Trash2, Edit, Printer, Users, DollarSign, AlertCircle, TrendingUp, FileText, X, ChevronRight } from 'lucide-react';
import { buildWatermarkCss, buildWatermarkMarkup } from '../../utils/watermarkPrint';

const money = v => 'Rs. ' + ((v||0)/100).toLocaleString();

/* Print transport report */
const printReport = (type, routes, school) => {
  const sName = school?.name||'IlmForge School';
  const date  = new Date().toLocaleDateString('en-PK');
  const sLogo = localStorage.getItem('schoolLogoPreview') || '';
  const watermarkCss = buildWatermarkCss({ mode: 'a4', color: '#0F4C45' });
  const watermarkHtml = buildWatermarkMarkup({ logo: sLogo, text: sName });

  const titles = {
    all:      'All Transport Routes Report',
    income:   'Transport Income Report',
    students: 'Connected Students Report',
    passes:   'Transport Passes',
  };

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${titles[type]}</title>
  <style>
    body{font-family:Arial,sans-serif;padding:24px;color:#1F2937;position:relative;overflow:hidden;}
    ${watermarkCss}
    h1,p,button,table,.footer,div{position:relative;z-index:1;}
    h1{color:#0F4C45;font-size:18px;margin:0 0 4px;}
    p{color:#6B7280;font-size:12px;margin:0 0 16px;}
    table{width:100%;border-collapse:collapse;}
    th{background:#0F4C45;color:#fff;padding:9px 12px;text-align:left;font-size:11.5px;}
    td{padding:8px 12px;border-bottom:1px solid #F3F4F6;font-size:12px;}
    tr:hover td{background:#F0FDFA;}
    .footer{margin-top:20px;padding-top:12px;border-top:1px dashed #E5E7EB;font-size:11px;color:#9CA3AF;text-align:center;}
    @media print{body{padding:0;}}
  </style></head><body>
    ${watermarkHtml}
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:4px;">
      <div><h1>${sName}</h1><p>${titles[type]} · ${date}</p></div>
      <div style="font-size:28px;">🚌</div>
    </div>
    <button onclick="window.print()" style="background:#0F766E;color:#fff;border:none;padding:7px 18px;border-radius:7px;cursor:pointer;margin-bottom:14px;font-size:12px;font-weight:700;">🖨 Print</button>
    <table>
      <thead><tr>
        <th>#</th><th>Route Name</th><th>Vehicle No</th><th>Driver</th><th>Monthly Fee</th>
      </tr></thead>
      <tbody>
        ${(routes||[]).map((r,i)=>`<tr>
          <td>${i+1}</td>
          <td><strong>${r.name}</strong></td>
          <td>${r.vehicleNo||'—'}</td>
          <td>${r.driverName||'—'}</td>
          <td><strong>${money(r.monthlyFee)}</strong></td>
        </tr>`).join('')}
        ${(!routes||routes.length===0)?'<tr><td colspan="5" style="text-align:center;padding:24px;color:#9CA3AF;">No routes added yet</td></tr>':''}
      </tbody>
    </table>
    <div class="footer">Generated by ${sName} · IlmForge · ${date}</div>
  </body></html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
};

export default function TransportPage() {
  const qc = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ name:'', vehicleNo:'', driverName:'', monthlyFee:'', description:'' });
  const [showOnboarding, setShowOnboarding] = useState(!localStorage.getItem('transport_visited'));

  const { data, isLoading } = useQuery({ queryKey:['transport'], queryFn:()=>api.get('/transport').then(r=>r.data.data) });
  const { data:school } = useQuery({ queryKey:['school-settings'], queryFn:()=>api.get('/settings/school').then(r=>r.data.data) });

  const routes = data || [];

  const add = useMutation({
    mutationFn: d => api.post('/transport', d),
    onSuccess: () => {
      toast.success('Route added!');
      qc.invalidateQueries(['transport']);
      setShowForm(false);
      setForm({ name:'', vehicleNo:'', driverName:'', monthlyFee:'', description:'' });
    },
    onError: err => toast.error(err.response?.data?.message || 'Failed'),
  });

  const remove = useMutation({
    mutationFn: id => api.delete('/transport/'+id),
    onSuccess: () => { toast.success('Route deleted'); qc.invalidateQueries(['transport']); },
  });

  const totalIncome = routes.reduce((s,r) => s+(r.monthlyFee||0), 0);

  return (
    <div className="page-content fade-up">
      {/* Header */}
      <div style={{ display:'flex', alignItems:'flex-start', justifyContent:'space-between', marginBottom:24 }}>
        <div>
          <h1 className="page-title">Transport Management</h1>
          <p className="page-subtitle">Manage school bus routes, vehicles and drivers</p>
        </div>
        <button className="btn btn-teal" onClick={()=>setShowForm(s=>!s)}>
          {showForm?<><X size={14}/> Cancel</>:<><Plus size={14}/> Add Route</>}
        </button>
      </div>

      {/* ── KPI Cards (matches screenshots exactly) ── */}
      <div className="grid-4" style={{ marginBottom:20 }}>
        <div className="kpi-card" style={{ background:'linear-gradient(135deg,#DC2626,#B91C1C)' }}>
          <div style={{ position:'absolute',right:16,top:16,opacity:.18 }}><Truck size={44}/></div>
          <div className="kpi-value">{routes.length}</div>
          <div className="kpi-label">Transport Routes</div>
          <div style={{ fontSize:11,marginTop:10,opacity:.7 }}>View Report →</div>
        </div>
        <div className="kpi-card" style={{ background:'linear-gradient(135deg,#D97706,#B45309)' }}>
          <div style={{ position:'absolute',right:16,top:16,opacity:.18 }}><Users size={44}/></div>
          <div className="kpi-value">0</div>
          <div className="kpi-label">Students Using Transport</div>
          <div style={{ fontSize:11,marginTop:10,opacity:.7 }}>View Report →</div>
        </div>
        <div className="kpi-card" style={{ background:'linear-gradient(135deg,#2563EB,#1D4ED8)' }}>
          <div style={{ position:'absolute',right:16,top:16,opacity:.18 }}><AlertCircle size={44}/></div>
          <div className="kpi-value">{money(0)}</div>
          <div className="kpi-label">Transport Dues Fees</div>
          <div style={{ fontSize:11,marginTop:10,opacity:.7 }}>View Report →</div>
        </div>
        <div className="kpi-card" style={{ background:'linear-gradient(135deg,#374151,#1F2937)' }}>
          <div style={{ position:'absolute',right:16,top:16,opacity:.18 }}><TrendingUp size={44}/></div>
          <div className="kpi-value">{money(totalIncome)}</div>
          <div className="kpi-label">Monthly Transport Income</div>
          <div style={{ fontSize:11,marginTop:10,opacity:.7 }}>View Report →</div>
        </div>
      </div>

      {/* ── Printable Reports Section ── */}
      <div className="card" style={{ marginBottom:20, borderLeft:'4px solid #0F766E' }}>
        <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:16 }}>
          <div style={{ width:32,height:32,borderRadius:8,background:'#F0FDFA',display:'flex',alignItems:'center',justifyContent:'center' }}>
            <FileText size={16} color="#0F766E"/>
          </div>
          <h3 style={{ margin:0, fontSize:14, fontWeight:700, color:'#111827' }}>Printable Transport Reports</h3>
        </div>
        <div style={{ display:'grid', gridTemplateColumns:'repeat(2,1fr)', gap:10 }}>
          {[
            { key:'all',      label:'All Transport Report',        desc:'List of all added transport routes.' },
            { key:'income',   label:'Transport Income',            desc:'List of all monthly income from transport fees.' },
            { key:'students', label:'Connected Students Report',   desc:'List of all routes with connected students.' },
            { key:'passes',   label:'Print Transport Passes',      desc:'Print transport passes for connected students.' },
          ].map(r => (
            <div key={r.key} style={{ display:'flex', alignItems:'center', justifyContent:'space-between', padding:'12px 14px', background:'#F9FAFB', borderRadius:9, border:'1px solid #E5E7EB' }}>
              <div>
                <div style={{ fontWeight:600, fontSize:13, color:'#111827' }}>{r.label}</div>
                <div style={{ fontSize:11.5, color:'#9CA3AF', marginTop:2 }}>{r.desc}</div>
              </div>
              <button className="btn btn-teal btn-sm" onClick={()=>printReport(r.key, routes, school)}>
                <Printer size={12}/> Print
              </button>
            </div>
          ))}
        </div>
        <p style={{ fontSize:11.5, color:'#9CA3AF', marginTop:10 }}>
          Note: Please ensure that all reports are printed in A4 size for optimal viewing. Adjust your printer settings accordingly.
        </p>
      </div>

      {/* ── Add Route Form ── */}
      {showForm && (
        <div className="card" style={{ marginBottom:16, borderTop:'3px solid #0F766E' }}>
          <h3 style={{ fontSize:14, fontWeight:700, color:'#111827', marginBottom:16 }}>Add New Route</h3>
          <div style={{ display:'grid', gridTemplateColumns:'repeat(2,1fr)', gap:12 }}>
            <div className="form-group">
              <label className="form-label">Route Name *</label>
              <input className="form-input" placeholder="e.g. G-8 to School" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>
            </div>
            <div className="form-group">
              <label className="form-label">Vehicle Number</label>
              <input className="form-input" placeholder="ABC-123" value={form.vehicleNo} onChange={e=>setForm({...form,vehicleNo:e.target.value})}/>
            </div>
            <div className="form-group">
              <label className="form-label">Driver Name</label>
              <input className="form-input" placeholder="Muhammad Akram" value={form.driverName} onChange={e=>setForm({...form,driverName:e.target.value})}/>
            </div>
            <div className="form-group">
              <label className="form-label">Monthly Fee (Rs.)</label>
              <input className="form-input" type="number" placeholder="1500" value={form.monthlyFee} onChange={e=>setForm({...form,monthlyFee:e.target.value})}/>
            </div>
            <div className="form-group" style={{ gridColumn:'span 2' }}>
              <label className="form-label">Description / Stops</label>
              <input className="form-input" placeholder="Route stops and details..." value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>
            </div>
          </div>
          <button className="btn btn-teal" onClick={()=>add.mutate({...form,monthlyFee:Math.round(parseFloat(form.monthlyFee||0)*100)})} disabled={!form.name||add.isPending}>
            <Plus size={14}/> {add.isPending?'Adding…':'Add Route'}
          </button>
        </div>
      )}

      {/* ── Onboarding Banner ── */}
      {showOnboarding && (
        <div style={{ background:'linear-gradient(135deg,#1B2F6E,#0073b7)', borderRadius:14, padding:'18px 22px', marginBottom:20, display:'flex', alignItems:'center', gap:16, position:'relative', overflow:'hidden' }}>
          <div style={{ fontSize:36 }}>🚌</div>
          <div style={{ flex:1 }}>
            <div style={{ fontWeight:700, fontSize:15, color:'white' }}>Welcome to Transport Management</div>
            <div style={{ fontSize:12.5, color:'rgba(255,255,255,.8)', marginTop:3 }}>Add bus routes, assign drivers, set fees and view connected students — all from one place.</div>
          </div>
          <button onClick={()=>{ localStorage.setItem('transport_visited','1'); setShowOnboarding(false); }}
            style={{ background:'rgba(255,255,255,.18)', border:'1px solid rgba(255,255,255,.35)', color:'white', borderRadius:8, padding:'6px 14px', cursor:'pointer', fontSize:12, fontWeight:600, flexShrink:0 }}>
            Got it <X size={11} style={{ marginLeft:4, verticalAlign:'middle' }}/>
          </button>
        </div>
      )}

      {/* ── Route Cards ── */}
      <div style={{ marginBottom:8, display:'flex', alignItems:'center', justifyContent:'space-between' }}>
        <h3 style={{ margin:0, fontSize:14, fontWeight:700, color:'#111827' }}>Transport Routes</h3>
        <span style={{ fontSize:12.5, color:'#9CA3AF' }}>{routes.length} routes</span>
      </div>
      {isLoading ? (
        <div className="loading-center"><div className="spinner"/></div>
      ) : routes.length === 0 ? (
        <div className="card">
          <div className="empty-state" style={{ padding:50 }}>
            <div className="empty-state-icon"><Truck size={40} style={{ opacity:.2 }}/></div>
            <div className="empty-state-text">No transport routes yet</div>
            <div className="empty-state-sub">Add your first route using the button above</div>
          </div>
        </div>
      ) : (
        <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill,minmax(260px,1fr))', gap:14 }}>
          {routes.map((r, i) => (
            <div key={r.id} style={{
              background:'rgba(255,255,255,0.65)', backdropFilter:'blur(16px)',
              borderRadius:14, padding:'18px 20px',
              border:'1px solid rgba(255,255,255,0.45)',
              boxShadow:'0 2px 12px rgba(0,0,0,.06)',
              animation:`ilm-fade-in 0.3s ease-out ${i*60}ms both`,
            }}>
              <div style={{ display:'flex', gap:12, alignItems:'center', marginBottom:12 }}>
                <div style={{ width:44, height:44, borderRadius:12, background:'linear-gradient(135deg,#1B2F6E,#0073b7)', display:'flex', alignItems:'center', justifyContent:'center', fontSize:22, flexShrink:0 }}>🚌</div>
                <div style={{ flex:1, minWidth:0 }}>
                  <div style={{ fontWeight:700, color:'#1e3a5f', fontSize:14, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{r.name}</div>
                  <div style={{ fontSize:11.5, color:'#64748b' }}>{r.vehicleNo ? `Vehicle: ${r.vehicleNo}` : 'No vehicle assigned'}</div>
                </div>
                <button className="btn btn-sm btn-icon" style={{ background:'#FEF2F2', border:'1px solid #FECACA', color:'#B91C1C', flexShrink:0 }}
                  onClick={()=>{ if(confirm('Delete route "'+r.name+'"?')) remove.mutate(r.id); }}>
                  <Trash2 size={12}/>
                </button>
              </div>
              <div style={{ fontSize:12.5, color:'#374151', display:'flex', flexDirection:'column', gap:5 }}>
                <div style={{ display:'flex', alignItems:'center', gap:6 }}><span>🚗</span><span>Driver: <strong>{r.driverName||'—'}</strong></span></div>
                {r.description && <div style={{ display:'flex', alignItems:'center', gap:6 }}><span>📍</span><span style={{ overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{r.description}</span></div>}
              </div>
              <div style={{ marginTop:12, paddingTop:12, borderTop:'1px solid rgba(0,0,0,.07)', display:'flex', alignItems:'center', justifyContent:'space-between' }}>
                <span style={{ fontSize:11, color:'#64748b', background:'#f0f9ff', borderRadius:6, padding:'3px 8px', border:'1px solid #bae6fd' }}>Monthly</span>
                <span style={{ fontWeight:800, fontSize:15, color:'#059669' }}>{money(r.monthlyFee)}</span>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
