/**
 * IlmForge — Transport Management
 * Full module with KPI cards, route management, and printable reports
 * exactly matching the reference screenshots
 */
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import api from '../../api/client';
import { Plus, Truck, Trash2, Edit, Printer, Users, DollarSign, AlertCircle, TrendingUp, FileText, X, ChevronRight } from 'lucide-react';
import { buildWatermarkCss, buildWatermarkMarkup } from '../../utils/watermarkPrint';

const money = v => 'Rs. ' + ((v||0)/100).toLocaleString();

/* Print transport report */
const printReport = (type, routes, school) => {
  const sName = school?.name||'IlmForge School';
  const date  = new Date().toLocaleDateString('en-PK');
  const sLogo = localStorage.getItem('schoolLogoPreview') || '';
  const watermarkCss = buildWatermarkCss({ mode: 'a4', color: '#0F4C45' });
  const watermarkHtml = buildWatermarkMarkup({ logo: sLogo, text: sName });

  const titles = {
    all:      'All Transport Routes Report',
    income:   'Transport Income Report',
    students: 'Connected Students Report',
    passes:   'Transport Passes',
  };

  const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${titles[type]}</title>
  <style>
    body{font-family:Arial,sans-serif;padding:24px;color:#1F2937;position:relative;overflow:hidden;}
    ${watermarkCss}
    h1,p,button,table,.footer,div{position:relative;z-index:1;}
    h1{color:#0F4C45;font-size:18px;margin:0 0 4px;}
    p{color:#6B7280;font-size:12px;margin:0 0 16px;}
    table{width:100%;border-collapse:collapse;}
    th{background:#0F4C45;color:#fff;padding:9px 12px;text-align:left;font-size:11.5px;}
    td{padding:8px 12px;border-bottom:1px solid #F3F4F6;font-size:12px;}
    tr:hover td{background:#F0FDFA;}
    .footer{margin-top:20px;padding-top:12px;border-top:1px dashed #E5E7EB;font-size:11px;color:#9CA3AF;text-align:center;}
    @media print{body{padding:0;}}
  </style></head><body>
    ${watermarkHtml}
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:4px;">
      <div><h1>${sName}</h1><p>${titles[type]} · ${date}</p></div>
      <div style="font-size:28px;">🚌</div>
    </div>
    <button onclick="window.print()" style="background:#0F766E;color:#fff;border:none;padding:7px 18px;border-radius:7px;cursor:pointer;margin-bottom:14px;font-size:12px;font-weight:700;">🖨 Print</button>
    <table>
      <thead><tr>
        <th>#</th><th>Route Name</th><th>Vehicle No</th><th>Driver</th><th>Monthly Fee</th>
      </tr></thead>
      <tbody>
        ${(routes||[]).map((r,i)=>`<tr>
          <td>${i+1}</td>
          <td><strong>${r.name}</strong></td>
          <td>${r.vehicleNo||'—'}</td>
          <td>${r.driverName||'—'}</td>
          <td><strong>${money(r.monthlyFee)}</strong></td>
        </tr>`).join('')}
        ${(!routes||routes.length===0)?'<tr><td colspan="5" style="text-align:center;padding:24px;color:#9CA3AF;">No routes added yet</td></tr>':''}
      </tbody>
    </table>
    <div class="footer">Generated by ${sName} · IlmForge · ${date}</div>
  </body></html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
};

export default function TransportPage() {
  const qc = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ name:'', vehicleNo:'', driverName:'', monthlyFee:'', description:'' });

  const { data, isLoading } = useQuery({ queryKey:['transport'], queryFn:()=>api.get('/transport').then(r=>r.data.data) });
  const { data:school } = useQuery({ queryKey:['school-settings'], queryFn:()=>api.get('/settings/school').then(r=>r.data.data) });

  const routes = data || [];

  const add = useMutation({
    mutationFn: d => api.post('/transport', d),
    onSuccess: () => {
      toast.success('Route added!');
      qc.invalidateQueries(['transport']);
      setShowForm(false);
      setForm({ name:'', vehicleNo:'', driverName:'', monthlyFee:'', description:'' });
    },
    onError: err => toast.error(err.response?.data?.message || 'Failed'),
  });

  const remove = useMutation({
    mutationFn: id => api.delete('/transport/'+id),
    onSuccess: () => { toast.success('Route deleted'); qc.invalidateQueries(['transport']); },
  });

  const totalIncome = routes.reduce((s,r) => s+(r.monthlyFee||0), 0);

  return (
    <div className="page-content fade-up">
      {/* Header */}
      <div style={{ display:'flex', alignItems:'flex-start', justifyContent:'space-between', marginBottom:24 }}>
        <div>
          <h1 className="page-title">Transport Management</h1>
          <p className="page-subtitle">Manage school bus routes, vehicles and drivers</p>
        </div>
        <button className="btn btn-teal" onClick={()=>setShowForm(s=>!s)}>
          {showForm?<><X size={14}/> Cancel</>:<><Plus size={14}/> Add Route</>}
        </button>
      </div>

      {/* ── KPI Cards (matches screenshots exactly) ── */}
      <div className="grid-4" style={{ marginBottom:20 }}>
        <div className="kpi-card" style={{ background:'linear-gradient(135deg,#DC2626,#B91C1C)' }}>
          <div style={{ position:'absolute',right:16,top:16,opacity:.18 }}><Truck size={44}/></div>
          <div className="kpi-value">{routes.length}</div>
          <div className="kpi-label">Transport Routes</div>
          <div style={{ fontSize:11,marginTop:10,opacity:.7 }}>View Report →</div>
        </div>
        <div className="kpi-card" style={{ background:'linear-gradient(135deg,#D97706,#B45309)' }}>
          <div style={{ position:'absolute',right:16,top:16,opacity:.18 }}><Users size={44}/></div>
          <div className="kpi-value">0</div>
          <div className="kpi-label">Students Using Transport</div>
          <div style={{ fontSize:11,marginTop:10,opacity:.7 }}>View Report →</div>
        </div>
        <div className="kpi-card" style={{ background:'linear-gradient(135deg,#2563EB,#1D4ED8)' }}>
          <div style={{ position:'absolute',right:16,top:16,opacity:.18 }}><AlertCircle size={44}/></div>
          <div className="kpi-value">{money(0)}</div>
          <div className="kpi-label">Transport Dues Fees</div>
          <div style={{ fontSize:11,marginTop:10,opacity:.7 }}>View Report →</div>
        </div>
        <div className="kpi-card" style={{ background:'linear-gradient(135deg,#374151,#1F2937)' }}>
          <div style={{ position:'absolute',right:16,top:16,opacity:.18 }}><TrendingUp size={44}/></div>
          <div className="kpi-value">{money(totalIncome)}</div>
          <div className="kpi-label">Monthly Transport Income</div>
          <div style={{ fontSize:11,marginTop:10,opacity:.7 }}>View Report →</div>
        </div>
      </div>

      {/* ── Printable Reports Section ── */}
      <div className="card" style={{ marginBottom:20, borderLeft:'4px solid #0F766E' }}>
        <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:16 }}>
          <div style={{ width:32,height:32,borderRadius:8,background:'#F0FDFA',display:'flex',alignItems:'center',justifyContent:'center' }}>
            <FileText size={16} color="#0F766E"/>
          </div>
          <h3 style={{ margin:0, fontSize:14, fontWeight:700, color:'#111827' }}>Printable Transport Reports</h3>
        </div>
        <div style={{ display:'grid', gridTemplateColumns:'repeat(2,1fr)', gap:10 }}>
          {[
            { key:'all',      label:'All Transport Report',        desc:'List of all added transport routes.' },
            { key:'income',   label:'Transport Income',            desc:'List of all monthly income from transport fees.' },
            { key:'students', label:'Connected Students Report',   desc:'List of all routes with connected students.' },
            { key:'passes',   label:'Print Transport Passes',      desc:'Print transport passes for connected students.' },
          ].map(r => (
            <div key={r.key} style={{ display:'flex', alignItems:'center', justifyContent:'space-between', padding:'12px 14px', background:'#F9FAFB', borderRadius:9, border:'1px solid #E5E7EB' }}>
              <div>
                <div style={{ fontWeight:600, fontSize:13, color:'#111827' }}>{r.label}</div>
                <div style={{ fontSize:11.5, color:'#9CA3AF', marginTop:2 }}>{r.desc}</div>
              </div>
              <button className="btn btn-teal btn-sm" onClick={()=>printReport(r.key, routes, school)}>
                <Printer size={12}/> Print
              </button>
            </div>
          ))}
        </div>
        <p style={{ fontSize:11.5, color:'#9CA3AF', marginTop:10 }}>
          Note: Please ensure that all reports are printed in A4 size for optimal viewing. Adjust your printer settings accordingly.
        </p>
      </div>

      {/* ── Add Route Form ── */}
      {showForm && (
        <div className="card" style={{ marginBottom:16, borderTop:'3px solid #0F766E' }}>
          <h3 style={{ fontSize:14, fontWeight:700, color:'#111827', marginBottom:16 }}>Add New Route</h3>
          <div style={{ display:'grid', gridTemplateColumns:'repeat(2,1fr)', gap:12 }}>
            <div className="form-group">
              <label className="form-label">Route Name *</label>
              <input className="form-input" placeholder="e.g. G-8 to School" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>
            </div>
            <div className="form-group">
              <label className="form-label">Vehicle Number</label>
              <input className="form-input" placeholder="ABC-123" value={form.vehicleNo} onChange={e=>setForm({...form,vehicleNo:e.target.value})}/>
            </div>
            <div className="form-group">
              <label className="form-label">Driver Name</label>
              <input className="form-input" placeholder="Muhammad Akram" value={form.driverName} onChange={e=>setForm({...form,driverName:e.target.value})}/>
            </div>
            <div className="form-group">
              <label className="form-label">Monthly Fee (Rs.)</label>
              <input className="form-input" type="number" placeholder="1500" value={form.monthlyFee} onChange={e=>setForm({...form,monthlyFee:e.target.value})}/>
            </div>
            <div className="form-group" style={{ gridColumn:'span 2' }}>
              <label className="form-label">Description / Stops</label>
              <input className="form-input" placeholder="Route stops and details..." value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>
            </div>
          </div>
          <button className="btn btn-teal" onClick={()=>add.mutate({...form,monthlyFee:Math.round(parseFloat(form.monthlyFee||0)*100)})} disabled={!form.name||add.isPending}>
            <Plus size={14}/> {add.isPending?'Adding…':'Add Route'}
          </button>
        </div>
      )}

      {/* ── Routes Table ── */}
      <div className="card" style={{ padding:0, overflow:'hidden' }}>
        <div style={{ padding:'14px 18px', borderBottom:'1px solid #F3F4F6', display:'flex', alignItems:'center', justifyContent:'space-between' }}>
          <h3 style={{ margin:0, fontSize:14, fontWeight:700, color:'#111827' }}>Transport Routes</h3>
          <span style={{ fontSize:12.5, color:'#9CA3AF' }}>{routes.length} routes</span>
        </div>
        {isLoading ? <div className="loading-center"><div className="spinner"/></div> : (
          <div className="table-wrap" style={{ borderRadius:0, border:'none' }}>
            <table className="data-table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Route Name</th>
                  <th>Vehicle No</th>
                  <th>Driver</th>
                  <th>Description</th>
                  <th>Monthly Fee</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {routes.map((r, i) => (
                  <tr key={r.id}>
                    <td style={{ color:'#9CA3AF', fontSize:12 }}>{i+1}</td>
                    <td>
                      <div style={{ display:'flex', alignItems:'center', gap:8 }}>
                        <div style={{ width:32,height:32,borderRadius:8,background:'#F0FDFA',display:'flex',alignItems:'center',justifyContent:'center',fontSize:16,flexShrink:0 }}>🚌</div>
                        <span style={{ fontWeight:700, fontSize:13 }}>{r.name}</span>
                      </div>
                    </td>
                    <td><span className="badge badge-blue">{r.vehicleNo||'—'}</span></td>
                    <td style={{ fontSize:13, color:'#374151' }}>{r.driverName||'—'}</td>
                    <td style={{ fontSize:12.5, color:'#6B7280', maxWidth:200, overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' }}>{r.description||'—'}</td>
                    <td style={{ fontWeight:700, color:'#059669', fontSize:14 }}>{money(r.monthlyFee)}</td>
                    <td>
                      <button className="btn btn-sm btn-icon" style={{ background:'#FEF2F2',border:'1px solid #FECACA',color:'#B91C1C' }}
                        onClick={()=>{ if(confirm('Delete route "'+r.name+'"?')) remove.mutate(r.id); }}>
                        <Trash2 size={12}/>
                      </button>
                    </td>
                  </tr>
                ))}
                {routes.length===0 && (
                  <tr><td colSpan={7}>
                    <div className="empty-state" style={{ padding:40 }}>
                      <div className="empty-state-icon"><Truck size={40} style={{ opacity:.2 }}/></div>
                      <div className="empty-state-text">No transport routes yet</div>
                      <div className="empty-state-sub">Add your first route using the button above</div>
                    </div>
                  </td></tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
