const crypto = require('crypto');

// FIX: platform.routes.js and license.routes.js each hardcoded their own
// LICENSE_SECRET fallback ('IlmForgeLicenseSecret2026' vs
// 'IlmForgeLicense@Secret#2026!OfflineKey') — if LICENSE_SECRET was ever
// unset in one environment but not the other, a key generated by one side
// would never verify against the other. Centralized so both always agree.
const LICENSE_SECRET = process.env.LICENSE_SECRET || 'IlmForgeLicense@Secret#2026!OfflineKey';

function generateLicenseKey(schoolId, plan, expiryDate) {
  const data = `ILMFORGE-${schoolId}-${plan}-${expiryDate.toISOString().split('T')[0]}`;
  const signature = crypto
    .createHmac('sha256', LICENSE_SECRET)
    .update(data)
    .digest('hex')
    .substring(0, 12)
    .toUpperCase();
  return `ILM-${String(schoolId).padStart(4, '0')}-${plan.toUpperCase().substring(0, 4)}-${signature}`;
}

function validateLicenseKey(key, schoolId, plan, expiryDate) {
  return key === generateLicenseKey(schoolId, plan, expiryDate);
}

module.exports = { LICENSE_SECRET, generateLicenseKey, validateLicenseKey };
